image: edbizarro/gitlab-ci-pipeline-php:7.3

variables:
  DB_DATABASE: healthcare
  DB_USERNAME: gitlabcicd
  DB_HOST: 3.136.233.168
  DB_PASSWORD: nhN2gJhzLmdFhS8C
  MAIL_USERNAME: info@healthcaretravels.com
  MAIL_PASSWORD: mmsbjvgnpfqvgjpi
  GOOGLE_MAPS_API_KEY: AIzaSyB-rD5XU_5kd1vcx_EiOg4syU_honD2XIg
  TWILIO_ACCOUNT_SID: AC3b5a19f4a401c9f3ca6c2c3c752f062f
  TWILIO_AUTH_TOKEN: 972d8905e785326e337d2d83b066836c
  TWILIO_MESSAGING_SERVICE_SID: MGb88f1274f4e7f8812b4b0b8b0db6688f

stages:
  - setup
  - deploy

deploy_production:
  stage: deploy
  script:
    - composer global require "hirak/prestissimo:^0.3" "laravel/envoy"
    - cp .env.example .env
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts --ignore-platform-reqs
    - php artisan key:generate
    - php artisan migrate
    - php artisan db:seed
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ~/.composer/vendor/bin/envoy run deploy --commit="$CI_COMMIT_SHA"
  environment:
    name: test
    url: http://3.136.233.168
  when: manual
  only:
    - develop
